// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLqRTQVVHJWJC21rDeISkNyF5iN0QqME',
    appId: '1:127807355825:web:824d2b4b0b5f58be0fdb90',
    messagingSenderId: '127807355825',
    projectId: 'my-ecommerce-app-123-1078f',
    authDomain: 'my-ecommerce-app-123-1078f.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-1078f.firebasestorage.app',
    measurementId: 'G-V535R2E39M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIPOmjCs0nPMLlNGhhvhGE88KAFEPMZk',
    appId: '1:127807355825:android:5b68d52b1e030edf0fdb90',
    messagingSenderId: '127807355825',
    projectId: 'my-ecommerce-app-123-1078f',
    storageBucket: 'my-ecommerce-app-123-1078f.firebasestorage.app',
  );

}